### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [DavidMGross/epictetus_discourses_george-long#1]
- Internal divisions should be `<section>` not `<article>`> I don't think these can be syndicated.

- Since we have `xml:lang` on `<i>`, we need the additional `body [xml|lang]{ font-style: italic; }` css

- `<i>that of an army prepared for battle,</i>`  and ` <i>present necessity.</i>` should probably be `<em>`, and comma/period goes outside italics

- There's many instances of em dashes crowding quotes in the endnotes for example `”⁠—Elizabeth Carter.`. These should have a space before the em dash and the dash and name should be within `<cite>`. You can search for `”⁠—` to find them.

- Let's remove the empty spans that you're using for indentation. Instead, add a class to those paragraphs with text-indent: 1em;.

- There's a few instances of large quotations which should be in `<blockquote>`s. For example the one starting `<p>“This is a wretched idea of friendship;`.  Since there is non-quoted text following the p, we should blockquote the quote. There's a few of these in the endnotes.

- We should spell `Encheiridion` as `Enchiridion` to be consistent in the corpus. You can put this in an `[Editorial]` commit.

- At the top of the endnotes, there's an intro from Long. But, in an ebook with popup endnotes it's unlikely the reader will ever see it. What if we pulled that part out and made it as a separate introduction, before the preface? Thoughts?

- This Long translation suffers from his constant bracketed alternative words, which I think I mentioned before. For example:

    `I do not care for any man who says anything else (different): in sophistical argument, I care for no man. Why then in greater matters do those annoy me who blame me? What is the cause of this perturbation? Nothing else than because in this matter (topic) I am not disciplined. For all knowledge (science) despises ignorance and the ignorant; and not only the sciences, but even the arts. Produce any shoemaker that you please, and he ridicules the many in respect to his own work787 (business).`

    That's both pedantic and distracting. It browbeats the reader. Do we really need an alternative gloss for the word "else" or "matter"? Did you give any thought to removing these in an `[Editorial]` commit?

-  Gleich und Gleich is not italicized; it's a title of a short poem so it gets quotes and `<span xml:lang>`.

- In your note in #528, SE should go in `<cite>` and you can write out `Standard Ebooks` for clarity (or your own name if you prefer). In any case we don't use title attrs.

- Colophon: 'translated from greek' needs the year it was translated in

- Metadata long description: Can we get a little more history/background on the discourses themselves, instead of a summary of Stoicism? The Wikipedia article has 7 sections so there's something to be said.

**Comment by davgross** [comment]
Too many issues for one issue. I'll fix the quick-and-easy ones and split the more complex ones off into their own issues.
