### ISSUE TITLE
Reconsider placement of Long's note regarding his sources

### ISSUE THREAD

**Issue by davgross** [DavidMGross/epictetus_discourses_george-long#2]
@acabal: "At the top of the endnotes, there's an intro from Long. But, in an ebook with popup endnotes it's unlikely the reader will ever see it. What if we pulled that part out and made it as a separate introduction, before the preface? Thoughts?"

**Comment by davgross** [comment]
I took those two paragraphs from Long's introduction. My reasoning was that Long refers to Elizabeth Carter and Johann Schweighauser and Hieronymous Wolf over and over in the endnotes, without giving the reader much context as to who they are and why he keeps bringing them up.

The two paragraphs I pilfered from his introduction explain this aspect of his notes, but they aren't very useful otherwise, and I don't think they'd make for a very good introduction on their own.

Maybe a stand-alone backmatter chapter, kind of a preface-to-the-endnotes?

**Comment by acabal** [comment]
Why not just keep the whole introduction?

**Comment by davgross** [comment]
That might work. I haven't read it that closely. My guess was that since Long's original work included the Discourses, the Enchiridion, and various Fragments, that the Introduction as-is might be awkwardly worded for just the Discourses. I can investigate more if you think that's the best avenue to take.
